server:
  port: 8000
  tomcat:
    threads:
      max: 1
      min-spare: 1
    max-connections: 30
    accept-count: 1
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
loader:
  temp-file-path: D:\temps
  enable-auto-merge: false
  enable-zero-merge: true
  process-type: RANDOM

logging:
  level:
    com.whistle.code.file: debug
  