server:
  port: 8000
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
loader:
  temp-file-path: D:\temps
  enable-auto-merge: true
  enable-zero-merge: false
#  process-type: RANDOM
  