# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "README.md"
      - ".gitignore"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '12.x' # optional

    - name: Install Dependencies
      run: npm install  
    # Runs a single command using the runners shell
    - name: Build projects
      run: npm run build
        
    - name: Commit files
      run: |
        cd docs/.vuepress/dist
        git init
        git add -A
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    # Runs a set of commands using the runners shell
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository:
        # Destination branch to push changes
        branch: gh-pages
        # Determines if force push is used
        force: true
        # Determines if --tags is used
        #tags: # optional
        # Directory to change to before pushing.
        directory: ./docs/.vuepress/dist/
    - name: git-mirror-action
      # You may pin to the exact commit or the version.
      # uses: mathisve/git-mirror-action@0e26d87bd1420836e3b68767929c997565c7028f
      uses: mathisve/git-mirror-action@v1.2
      with:
        # url of the repository you want to mirror
        originalURL: https://github.com/Gentvel/whistle.git
        # branch in the original repository you want to mirror. Defaults to `master`
        originalBranch: gh-pages# optional
        # url of the repository you want the mirror to go in
        mirrorURL: https://gitee.com/gentvel/whistle.git
        # branch that will be created or pushed into. Defaults to `mirror`
        mirrorBranch: gh-pages# optional
        # Base64 encoded Personal Access Token
        pat: ${{ secrets.GITEE_TOKEN }}
        # whether to use the `--force` argument when pushing to the mirror repository. Defaults to false
        force: true# optional
        # whether or not you want the output to be verbose. Defaults to false
        verbose: false# optional
        # whether or not you want to transfer tags. Defaults to false
        tags: false # optional  
